blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/orgs/community/discussions
    about: Please ask and answer questions here.
  - name: GitHub Security Bug Bounty
    url: https://bounty.github.com/
    about: Please report security vulnerabilities here.

preset_config:
  - name: "new-texture-pack"
    content: |
      ### Texture Pack Name
      **Descripción:**
      [Describe brevemente el nombre del Texture Pack aquí]

      ### Version
      **Versión:**
      [Indica la versión del Texture Pack]

      ### Drag yui file here
      [Arrastra y suelta el archivo YUI aquí para subirlo]
