name: Texture Pack link
description: Create a new texture pack request.
title: "[Texture Pack]: "
labels: ["enhancement"]
projects: ["octo-org/1", "octo-org/44"]
assignees:
  - octocat
body:
  - type: textarea
    id: texture_pack_file
    attributes:
      label: Drag file here
      description: Upload your texture pack file (ZIP format).
      placeholder: Drag and drop your file here or click to upload.
    validations:
      required: true
