name: Texture Pack
description: Create a new texture pack request.
title: "[Texture Pack]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for submitting your texture pack request!
  - type: input
    id: texture_pack_name
    attributes:
      label: Texture Pack Name
      description: Enter the name of your texture pack.
      placeholder: My Awesome Texture Pack
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a brief description of your texture pack.
      placeholder: Describe your texture pack here.
    validations:
      required: true

