name: Crear Carpeta y Descomprimir

on:
  issue_comment:
    types: [created]

jobs:
  create_folder_and_unzip:
    if: contains(github.event.comment.body, '!accept')
    runs-on: ubuntu-latest
    steps:
      - name: Obtener datos del issue
        id: extract_data
        run: |
          # Obtener el cuerpo del issue
          ISSUE_BODY=$(curl -s "https://api.github.com/repos/iArtie/texture-shop-index/issues/1" | findstr /C:"\"body\":")

          # Extraer el Texture Pack Name y el Download Link
          TEXTURE_PACK_NAME=$(echo "$ISSUE_BODY" | grep -oP '(?<=### Texture Pack Name\n)[^\n]+')
          DOWNLOAD_LINK=$(echo "$ISSUE_BODY" | grep -oP '(?<=### Drag file here\n\[Link\]\()[^\)]+')

          echo "Texture Pack Name: $TEXTURE_PACK_NAME"
          echo "Download Link: $DOWNLOAD_LINK"

          # Verificar el valor de TEXTURE_PACK_NAME antes de crear la carpeta
          echo "Valor de TEXTURE_PACK_NAME: $TEXTURE_PACK_NAME"

          # Crear carpeta, descargar y descomprimir archivos
          mkdir "$TEXTURE_PACK_NAME"
          wget -O temp.zip "$DOWNLOAD_LINK"
          unzip temp.zip -d "$TEXTURE_PACK_NAME"

      - name: Confirmar cambios
        run: |
          git add .
          git commit -m "Add Texture Pack: $TEXTURE_PACK_NAME"
          git push origin HEAD
        working-directory: ${{ github.workspace }}
