name: Crear Carpeta y Descomprimir

on:
  issue_comment:
    types: [created]

jobs:
  create_folder_and_unzip:
    if: contains(github.event.comment.body, '!accept')
    runs-on: ubuntu-latest
    steps:
      - name: Obtener datos del issue
        id: extract_data
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: issue } = await github.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });

            const lines = issue.body.split('\n');
            let texturePackName = '';
            let downloadLink = '';

            lines.forEach(line => {
              if (line.startsWith('### Texture Pack Name')) {
                texturePackName = line.split(':')[1].trim();
              }
              if (line.startsWith('### Drag file here')) {
                const linkStartIndex = line.indexOf('(') + 1;
                const linkEndIndex = line.indexOf(')');
                downloadLink = line.substring(linkStartIndex, linkEndIndex);
              }
            });

            console.log(`Texture Pack Name: ${texturePackName}`);
            console.log(`Download Link: ${downloadLink}`);

            return { texturePackName, downloadLink };

      - name: Crear carpeta
        run: mkdir ${{ steps.extract_data.outputs.texturePackName }}

      - name: Descargar y descomprimir archivos
        run: |
          wget -O temp.zip ${{ steps.extract_data.outputs.downloadLink }}
          unzip temp.zip -d ${{ steps.extract_data.outputs.texturePackName }}
        working-directory: ${{ github.workspace }}
