name: Extract Texture Pack

on:
  issue_comment:
    types: [created]  # Se activa cuando se crea un comentario en una issue

jobs:
  extract_texture_pack:
    runs-on: ubuntu-latest

    steps:
    - name: Check if comment triggers workflow
      if: github.event.comment.body == '!accept'  # Verifica si el comentario es '!accept'
      run: |
        issue_number=$(echo "$GITHUB_EVENT_PATH" | jq -r '.issue.number')
        echo "Workflow triggered by comment on issue #$issue_number"
        curl -s "https://api.github.com/repos/$GITHUB_REPOSITORY/issues/$issue_number" | grep "\"body\":"
      else:
        echo "No action needed"
        exit 0

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Extract Texture Pack
      run: |
        body=$(curl -s "https://api.github.com/repos/$GITHUB_REPOSITORY/issues/$issue_number" | grep "\"body\":")
        tpname=$(echo "$body" | grep -oP '(?<=### Texture Pack Name\n\n)[^\n\r]+')
        zip_url=$(echo "$body" | grep -oP '(?<=### Drag file here\n\n\[.*\]\()(.*)(?=\))')
        wget -O texture_pack.zip $zip_url
        unzip -q texture_pack.zip -d $tpname
        rm texture_pack.zip

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Extracted Texture Pack"
        git push
