name: Procesar archivo de issue

on:
  issue_comment:
    types: [created]

jobs:
  procesar-archivo:
    runs-on: ubuntu-latest
    permissions: write-all
      
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        
      - name: Verificar comentario "!accept"
        id: verificar-comentario
        run: |
          echo result=`python verify_staff.py ${{ github.event.comment.user.login }}` >> $GITHUB_OUTPUT

      - name: Setup Python
        if: steps.verificar-comentario.outputs.result == 'Yes' && github.event.comment.body == '!accept'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Extract texture pack
        if: steps.verificar-comentario.outputs.result == 'Yes' && github.event.comment.body == '!accept'
        run: |
          pip install requests
          python upload_folder.py
        env:
          BODY: ${{ github.event.issue.body }}

      - name: Setup bot
        if: steps.verificar-comentario.outputs.result == 'Yes' && github.event.comment.body == '!accept'
        run: |
          python test_bot.py
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_ID: ${{ github.event.issue.number }}
