name: Unzip Texture Pack

on:
  issue_comment:
    types: [created]

jobs:
  unzip:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '!accept')

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install zipfile36

      - name: Unzip texture pack
        run: |
          mkdir -p "$GITHUB_WORKSPACE/Texture_Packs"
          mkdir -p "$GITHUB_WORKSPACE/Texture_Packs/${{ fromJson(github.event.issue.body).id }}"
          python -c "import zipfile; zipfile.ZipFile('$GITHUB_EVENT_PATH/${{ fromJson(github.event.issue.body).id }}').extractall('$GITHUB_WORKSPACE/Texture_Packs/${{ fromJson(github.event.issue.body).id }}')"
        env:
          TEXTURE_PACK_NAME: ${{ fromJson(github.event.issue.body).id }}
          TEXTURE_PACK_FILE: ${{ fromJson(github.event.issue.body).id }}
