name: Extract Texture Pack

on:
  issue_comment:
    types: [created]  # Se activa cuando se crea un comentario en una issue

jobs:
  extract_texture_pack:
    runs-on: ubuntu-latest

    steps:
    - name: Check if comment triggers workflow
      run: |
        comment=$(jq -r '.comment.body' $GITHUB_EVENT_PATH)
        if [[ "$comment" == "!accept" ]]; then
          echo "Workflow triggered by comment"
          exit 0
        else
          echo "No action needed"
          exit 1
        fi

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Extract Texture Pack
      run: |
        body=$(curl -s "$GITHUB_API_URL/repos/$GITHUB_REPOSITORY/issues/$ISSUE_NUMBER" | jq -r '.body')
        tpname=$(echo "$body" | grep -oP '(?<=### Texture Pack Name\n\n)[^\n\r]+')
        zip_url=$(echo "$body" | grep -oP '(?<=### Drag file here\n\n\[.*\]\()(.*)(?=\))')
        wget -O texture_pack.zip $zip_url
        unzip -q texture_pack.zip -d $tpname
        rm texture_pack.zip

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Extracted Texture Pack"
        git push
