name: Procesar archivo de issue

on:
  issue_comment:
    types: [created]

jobs:
  procesar-archivo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        
      - name: Verificar comentario "!accept"
        id: verificar-comentario
        run: |
          comentario=$(jq -r .comment.body "${GITHUB_EVENT_PATH}")
          if [[ "$comentario" == "!accept" ]]; then
            echo "::set-output name=accept::true"
          else
            echo "::set-output name=accept::false"
          fi

      - name: Setup Python
        if: steps.verificar-comentario.outputs.accept == 'true'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 

      - name: Setup bot
        if: steps.verificar-comentario.outputs.accept == 'true'
        run: |
          pip install requests
          python test_bot.py
        env:
          TOKEN: ${{ secrets.TEXTURESHOP_TOKEN }}
          ISSUE_ID: ${{ github.event.issue.number }}
