name: Crear Carpeta y Descomprimir

on:
  push:
    branches:
      - main

jobs:
  create_folder_and_unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Crear carpeta
        run: mkdir ${{ github.workspace }}/${{ github.event.inputs.texture_pack_name }}

      - name: Descargar y descomprimir archivos
        run: |
          wget -O temp.zip ${{ github.event.inputs.download_link }}
          unzip temp.zip -d ${{ github.workspace }}/${{ github.event.inputs.texture_pack_name }}
        working-directory: ${{ github.workspace }}
