name: Procesar archivo de issue

on:
  issue_comment:
    types: [created]

jobs:
  procesar-archivo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Verificar comentario "!accept"
        id: verificar-comentario
        run: |
          comentario=$(jq -r .comment.body "${GITHUB_EVENT_PATH}")
          if [[ "$comentario" == "!accept" ]]; then
            echo "::set-output name=accept::true"
          else
            echo "::set-output name=accept::false"
          fi

      - name: Obtener enlace de archivo y descargar
        if: steps.verificar-comentario.outputs.accept == 'true'
        id: obtener-enlace
        run: |
          enlace=$(awk '/^### Drag file here/ {getline; print substr($0, index($0, "(")+1, length($0)-index($0, ")")-1)}' <<< "${{ github.event.issue.body }}")
          curl -o "archivo.zip" "$enlace"

      - name: Crear carpeta "Texture Packs" si no existe
        if: steps.verificar-comentario.outputs.accept == 'true'
        run: |
          mkdir -p "Texture Packs"

      - name: Mover archivo a "Texture Packs"
        if: steps.verificar-comentario.outputs.accept == 'true'
        run: |
          mv "archivo.zip" "Texture Packs/"
